{
  "language": "Vietnamese",
  "conventions": {
    "preferredLanguage": "Vietnamese",
    "comments": {
      "preferredLanguage": "Vietnamese"
    },
    "documentation": {
      "preferredLanguage": "Vietnamese"
    }
  }
}